name: e_commerce_admin_panel
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  lottie: ^3.1.3
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_dropzone: ^4.2.0
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^6.1.0
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.2
  web: ^1.1.0
  http: ^1.2.2
  fl_chart: ^0.69.0
  data_table_2: ^2.5.15
  url_strategy: ^0.3.0
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  firebase_storage: ^12.3.5
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Fonts section
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-BlackItalic.ttf
          style: italic
          weight: 700

  # Assets section for images
  assets:
    - assets/icon/
    - assets/logo/
    - assets/images/animation/
    - assets/images/banners/
    - assets/images/onboarding_images/
    - assets/images/payment_method/
    - assets/images/products/
    - assets/images/review_user/
    - assets/images/user/
