// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPdR3g9VX_VPmFljY7y8TdEawKu8FdDTQ',
    appId: '1:609412979234:web:ca8b48f30b69c00132487b',
    messagingSenderId: '609412979234',
    projectId: 'quiz-e82d1',
    authDomain: 'quiz-e82d1.firebaseapp.com',
    storageBucket: 'quiz-e82d1.appspot.com',
    measurementId: 'G-7FDJHZY7H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmYwIxp0IYthCYYkhneK7SpPyEdkiRfWk',
    appId: '1:609412979234:android:6b91feb06461934332487b',
    messagingSenderId: '609412979234',
    projectId: 'quiz-e82d1',
    storageBucket: 'quiz-e82d1.appspot.com',
  );
}
